// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Nyk.SimpleArithmeticLib.Tests")>]
[<assembly: AssemblyProductAttribute("Nyk.SimpleArithmeticLib")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-06-05T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","b885080c0b996a5a4f093d89b1ccb99cb384987e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Nyk.SimpleArithmeticLib.Tests"
    let [<Literal>] AssemblyProduct = "Nyk.SimpleArithmeticLib"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-06-05T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyInformationalVersion = "1.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "b885080c0b996a5a4f093d89b1ccb99cb384987e"
